// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	client "sigs.k8s.io/controller-runtime/pkg/client"

	context "context"

	mock "github.com/stretchr/testify/mock"

	v1 "k8s.io/api/core/v1"
)

// MockGitComponent is an autogenerated mock type for the GitComponent type
type MockGitComponent struct {
	mock.Mock
}

type MockGitComponent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGitComponent) EXPECT() *MockGitComponent_Expecter {
	return &MockGitComponent_Expecter{mock: &_m.Mock}
}

// GetAPIEndpoint provides a mock function with no fields
func (_m *MockGitComponent) GetAPIEndpoint() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAPIEndpoint")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockGitComponent_GetAPIEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAPIEndpoint'
type MockGitComponent_GetAPIEndpoint_Call struct {
	*mock.Call
}

// GetAPIEndpoint is a helper method to define mock.On call
func (_e *MockGitComponent_Expecter) GetAPIEndpoint() *MockGitComponent_GetAPIEndpoint_Call {
	return &MockGitComponent_GetAPIEndpoint_Call{Call: _e.mock.On("GetAPIEndpoint")}
}

func (_c *MockGitComponent_GetAPIEndpoint_Call) Run(run func()) *MockGitComponent_GetAPIEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitComponent_GetAPIEndpoint_Call) Return(_a0 string) *MockGitComponent_GetAPIEndpoint_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGitComponent_GetAPIEndpoint_Call) RunAndReturn(run func() string) *MockGitComponent_GetAPIEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// GetApplication provides a mock function with no fields
func (_m *MockGitComponent) GetApplication() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetApplication")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockGitComponent_GetApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApplication'
type MockGitComponent_GetApplication_Call struct {
	*mock.Call
}

// GetApplication is a helper method to define mock.On call
func (_e *MockGitComponent_Expecter) GetApplication() *MockGitComponent_GetApplication_Call {
	return &MockGitComponent_GetApplication_Call{Call: _e.mock.On("GetApplication")}
}

func (_c *MockGitComponent_GetApplication_Call) Run(run func()) *MockGitComponent_GetApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitComponent_GetApplication_Call) Return(_a0 string) *MockGitComponent_GetApplication_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGitComponent_GetApplication_Call) RunAndReturn(run func() string) *MockGitComponent_GetApplication_Call {
	_c.Call.Return(run)
	return _c
}

// GetBranches provides a mock function with no fields
func (_m *MockGitComponent) GetBranches() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBranches")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockGitComponent_GetBranches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBranches'
type MockGitComponent_GetBranches_Call struct {
	*mock.Call
}

// GetBranches is a helper method to define mock.On call
func (_e *MockGitComponent_Expecter) GetBranches() *MockGitComponent_GetBranches_Call {
	return &MockGitComponent_GetBranches_Call{Call: _e.mock.On("GetBranches")}
}

func (_c *MockGitComponent_GetBranches_Call) Run(run func()) *MockGitComponent_GetBranches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitComponent_GetBranches_Call) Return(_a0 []string) *MockGitComponent_GetBranches_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGitComponent_GetBranches_Call) RunAndReturn(run func() []string) *MockGitComponent_GetBranches_Call {
	_c.Call.Return(run)
	return _c
}

// GetGitURL provides a mock function with no fields
func (_m *MockGitComponent) GetGitURL() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetGitURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockGitComponent_GetGitURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGitURL'
type MockGitComponent_GetGitURL_Call struct {
	*mock.Call
}

// GetGitURL is a helper method to define mock.On call
func (_e *MockGitComponent_Expecter) GetGitURL() *MockGitComponent_GetGitURL_Call {
	return &MockGitComponent_GetGitURL_Call{Call: _e.mock.On("GetGitURL")}
}

func (_c *MockGitComponent_GetGitURL_Call) Run(run func()) *MockGitComponent_GetGitURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitComponent_GetGitURL_Call) Return(_a0 string) *MockGitComponent_GetGitURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGitComponent_GetGitURL_Call) RunAndReturn(run func() string) *MockGitComponent_GetGitURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetHost provides a mock function with no fields
func (_m *MockGitComponent) GetHost() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHost")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockGitComponent_GetHost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHost'
type MockGitComponent_GetHost_Call struct {
	*mock.Call
}

// GetHost is a helper method to define mock.On call
func (_e *MockGitComponent_Expecter) GetHost() *MockGitComponent_GetHost_Call {
	return &MockGitComponent_GetHost_Call{Call: _e.mock.On("GetHost")}
}

func (_c *MockGitComponent_GetHost_Call) Run(run func()) *MockGitComponent_GetHost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitComponent_GetHost_Call) Return(_a0 string) *MockGitComponent_GetHost_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGitComponent_GetHost_Call) RunAndReturn(run func() string) *MockGitComponent_GetHost_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function with no fields
func (_m *MockGitComponent) GetName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockGitComponent_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type MockGitComponent_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *MockGitComponent_Expecter) GetName() *MockGitComponent_GetName_Call {
	return &MockGitComponent_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *MockGitComponent_GetName_Call) Run(run func()) *MockGitComponent_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitComponent_GetName_Call) Return(_a0 string) *MockGitComponent_GetName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGitComponent_GetName_Call) RunAndReturn(run func() string) *MockGitComponent_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// GetNamespace provides a mock function with no fields
func (_m *MockGitComponent) GetNamespace() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNamespace")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockGitComponent_GetNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNamespace'
type MockGitComponent_GetNamespace_Call struct {
	*mock.Call
}

// GetNamespace is a helper method to define mock.On call
func (_e *MockGitComponent_Expecter) GetNamespace() *MockGitComponent_GetNamespace_Call {
	return &MockGitComponent_GetNamespace_Call{Call: _e.mock.On("GetNamespace")}
}

func (_c *MockGitComponent_GetNamespace_Call) Run(run func()) *MockGitComponent_GetNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitComponent_GetNamespace_Call) Return(_a0 string) *MockGitComponent_GetNamespace_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGitComponent_GetNamespace_Call) RunAndReturn(run func() string) *MockGitComponent_GetNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlatform provides a mock function with no fields
func (_m *MockGitComponent) GetPlatform() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPlatform")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockGitComponent_GetPlatform_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlatform'
type MockGitComponent_GetPlatform_Call struct {
	*mock.Call
}

// GetPlatform is a helper method to define mock.On call
func (_e *MockGitComponent_Expecter) GetPlatform() *MockGitComponent_GetPlatform_Call {
	return &MockGitComponent_GetPlatform_Call{Call: _e.mock.On("GetPlatform")}
}

func (_c *MockGitComponent_GetPlatform_Call) Run(run func()) *MockGitComponent_GetPlatform_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitComponent_GetPlatform_Call) Return(_a0 string) *MockGitComponent_GetPlatform_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGitComponent_GetPlatform_Call) RunAndReturn(run func() string) *MockGitComponent_GetPlatform_Call {
	_c.Call.Return(run)
	return _c
}

// GetRPMActivationKey provides a mock function with given fields: _a0, _a1
func (_m *MockGitComponent) GetRPMActivationKey(_a0 context.Context, _a1 client.Client) (string, string, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetRPMActivationKey")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, client.Client) (string, string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.Client) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.Client) string); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, client.Client) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockGitComponent_GetRPMActivationKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRPMActivationKey'
type MockGitComponent_GetRPMActivationKey_Call struct {
	*mock.Call
}

// GetRPMActivationKey is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 client.Client
func (_e *MockGitComponent_Expecter) GetRPMActivationKey(_a0 interface{}, _a1 interface{}) *MockGitComponent_GetRPMActivationKey_Call {
	return &MockGitComponent_GetRPMActivationKey_Call{Call: _e.mock.On("GetRPMActivationKey", _a0, _a1)}
}

func (_c *MockGitComponent_GetRPMActivationKey_Call) Run(run func(_a0 context.Context, _a1 client.Client)) *MockGitComponent_GetRPMActivationKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(client.Client))
	})
	return _c
}

func (_c *MockGitComponent_GetRPMActivationKey_Call) Return(_a0 string, _a1 string, _a2 error) *MockGitComponent_GetRPMActivationKey_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockGitComponent_GetRPMActivationKey_Call) RunAndReturn(run func(context.Context, client.Client) (string, string, error)) *MockGitComponent_GetRPMActivationKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetRenovateConfig provides a mock function with given fields: _a0, _a1
func (_m *MockGitComponent) GetRenovateConfig(_a0 *v1.Secret, _a1 string) (string, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetRenovateConfig")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1.Secret, string) (string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*v1.Secret, string) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*v1.Secret, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitComponent_GetRenovateConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRenovateConfig'
type MockGitComponent_GetRenovateConfig_Call struct {
	*mock.Call
}

// GetRenovateConfig is a helper method to define mock.On call
//   - _a0 *v1.Secret
//   - _a1 string
func (_e *MockGitComponent_Expecter) GetRenovateConfig(_a0 interface{}, _a1 interface{}) *MockGitComponent_GetRenovateConfig_Call {
	return &MockGitComponent_GetRenovateConfig_Call{Call: _e.mock.On("GetRenovateConfig", _a0, _a1)}
}

func (_c *MockGitComponent_GetRenovateConfig_Call) Run(run func(_a0 *v1.Secret, _a1 string)) *MockGitComponent_GetRenovateConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1.Secret), args[1].(string))
	})
	return _c
}

func (_c *MockGitComponent_GetRenovateConfig_Call) Return(_a0 string, _a1 error) *MockGitComponent_GetRenovateConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitComponent_GetRenovateConfig_Call) RunAndReturn(run func(*v1.Secret, string) (string, error)) *MockGitComponent_GetRenovateConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetRepository provides a mock function with no fields
func (_m *MockGitComponent) GetRepository() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRepository")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockGitComponent_GetRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepository'
type MockGitComponent_GetRepository_Call struct {
	*mock.Call
}

// GetRepository is a helper method to define mock.On call
func (_e *MockGitComponent_Expecter) GetRepository() *MockGitComponent_GetRepository_Call {
	return &MockGitComponent_GetRepository_Call{Call: _e.mock.On("GetRepository")}
}

func (_c *MockGitComponent_GetRepository_Call) Run(run func()) *MockGitComponent_GetRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitComponent_GetRepository_Call) Return(_a0 string) *MockGitComponent_GetRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGitComponent_GetRepository_Call) RunAndReturn(run func() string) *MockGitComponent_GetRepository_Call {
	_c.Call.Return(run)
	return _c
}

// GetToken provides a mock function with no fields
func (_m *MockGitComponent) GetToken() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitComponent_GetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToken'
type MockGitComponent_GetToken_Call struct {
	*mock.Call
}

// GetToken is a helper method to define mock.On call
func (_e *MockGitComponent_Expecter) GetToken() *MockGitComponent_GetToken_Call {
	return &MockGitComponent_GetToken_Call{Call: _e.mock.On("GetToken")}
}

func (_c *MockGitComponent_GetToken_Call) Run(run func()) *MockGitComponent_GetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitComponent_GetToken_Call) Return(_a0 string, _a1 error) *MockGitComponent_GetToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitComponent_GetToken_Call) RunAndReturn(run func() (string, error)) *MockGitComponent_GetToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGitComponent creates a new instance of MockGitComponent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGitComponent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGitComponent {
	mock := &MockGitComponent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
