# permissions for end users to view dependencyupdatechecks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mintmaker
    app.kubernetes.io/managed-by: kustomize
  name: dependencyupdatecheck-viewer-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - dependencyupdatechecks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - dependencyupdatechecks/status
  verbs:
  - get
