apiVersion: appstudio.redhat.com/v1alpha1
kind: DependencyUpdateCheck
metadata:
  labels:
    app.kubernetes.io/name: mintmaker
    app.kubernetes.io/managed-by: kustomize
  generateName: dependencyupdatecheck-
spec:
  workspaces:
  - workspace: "workspace1"
    applications:
    - application: "application1"
      components:
      - "component1"
      - "component2"
    - application: "application2"
  - workspace: "workspace2"
